#base image
FROM node:0.12.4-slim

# Exclude npm cache from the image
VOLUME /root/.npm

#add files ad set workdir
COPY . /drbx-js
WORKDIR /drbx-js

#install dependecys
RUN apt-get update && \
    apt-get install -y g++ python bzip2\
                       libfreetype6 make \
                       libfontconfig curl && \
    npm install -g tape-run && \
    npm install -g browserify && \
    npm install -g phantomjs && \
    npm cache clean && \
    npm install

#launch
CMD npm test
